apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sck
spec:
  chart:
    name: splunk-connect-for-kubernetes
    repository: https://splunk.github.io/splunk-connect-for-kubernetes/
    version: 1.4.7
  values:
    #global settings
    global:
      logLevel: info 
      splunk:
        hec:
          protocol: ##PROTO##
          insecureSSL: ##INSECURE_SSL##
          host: "##HOST##"
          token: "##TOKEN##"
          port: ##PORT##
      kubernetes:
        clusterName: "##CLUSTER_NAME##" 

    #local config for logging chart
    splunk-kubernetes-logging:
      enabled: true
      logLevel: info 
      containers:
        logFormatType: cri
        logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
      fluentd:
        path: "/var/log/containers/*_sc4snmp_*.log,/var/log/containers/*_sck_*.log"
      kubernetes:
        securityContext: true
      journalLogPath: /var/log/journal
      buffer:
        "@type": memory
        total_limit_size: 600m
        chunk_limit_size: 10m
        chunk_limit_records: 100000
        flush_interval: 5s
        flush_thread_count: 1
        overflow_action: block
        retry_max_times: 10
        retry_type: periodic
      k8sMetadata:
        # Pod labels to collect
        podLabels:
          - app
          - k8s-app
          - release
          - environment
          - tier
      sourcetypePrefix: "kube"
      splunk:
        hec:
          indexName: ##EVENTS_INDEX##
      logs:
        sck:
          from:
            pod: sck-sck-splunk-kubernetes-
            container: splunk-fluentd-k8s-
          multiline:
            firstline: /^\d{4}-\d{2}-\d{2}\s\d{2}\:\d{2}\:\d{2}\s\+\d{4}\s\[\w+\]\:/
            separator: "\n"
            flushInterval: 5 

    #local config for objects chart
    splunk-kubernetes-objects:
      enabled: false
      rbac:
        create: true
      serviceAccount:
        create: true
        name: splunk-kubernetes-objects
      kubernetes:
        insecureSSL: true
      objects:
        core:
          v1:
            [{ "name": "pods", "interval": "300s" },{ "name": "nodes", "interval": "300s" },{ "name": "component_statuses", "interval": "300s" },{ "name": "namespaces", "interval": "300s" },{ "name": "services", "interval": "300s" },{ "name": "events", "mode": "watch" }]
      splunk:
        hec:
          indexName: ##META_INDEX##

    #local config for metrics chart
    splunk-kubernetes-metrics:
      enabled: false
      metricsInterval: 60s
      kubernetes:
        kubeletPort: 10255
        kubeletPortAggregator: 10250
        useRestClientSSL: false
        insecureSSL: true
      rbac:
        create: true
      serviceAccount:
        create: true
        name: splunk-kubernetes-metrics
      splunk:
        hec:
          indexName: ##METRICS_INDEX##
      customFilters:
        node:
          tag: "kube.node.**"
          type: record_modifier
          body: |-
            <record>
              entity_type k8s_node
            </record>
        pod:
          tag: "kube.pod.**"
          type: record_modifier
          body: |-
            <record>
              entity_type k8s_pod
            </record>
