apiVersion: v1
kind: Service
metadata:
  name: sc4-snmp-traps
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: ##SHAREDIP##
  ports:
    - port: 162
      targetPort: 2162
      protocol: UDP
  selector:
    app: sc4-snmp-traps
