apiVersion: apps/v1
kind: Deployment
metadata:
  name: mib-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc4-snmp-mib-server
  template:
    metadata:
      labels:
        app: sc4-snmp-mib-server
    spec:
      containers:
        - name: mib-server
          image: ghcr.io/splunk/splunk-connect-for-snmp-mib-server:1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MIBS_FILES_URL
              value: "http://$(MIB_SERVER_SERVICE_SERVICE_HOST):$(MIB_SERVER_SERVICE_SERVICE_PORT)/files/asn1/@mib@"
            - name: MONGO_SERVICE_SERVICE_HOST
              value: cache-mongodb
            - name: MONGO_SERVICE_SERVICE_PORT
              value: "27017"
            - name: MONGO_USER
              value: root
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: cache-mongodb
                  key: mongodb-root-password
