kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo
spec:
  storageClassName: mongo
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---